Add markdown support for description field
rocketden/main pull request #109
Opened 2021-03-01 09:21 UTC by alankbi

### List of Changes:

* Add markdown support for description field
* Change database description field type to TEXT (for unlimited length)
* Change game page problem display to properly show multi-line and markdown text

### Notes:

* This PR uses this markdown library: https://github.com/outline/rich-markdown-editor
  * It's very fancy and high-performing, though the tradeoff might be lower flexibility/reliance on a company product

### Screencast and Images:

[Screencast of markdown editing and viewing behavior](https://www.loom.com/share/7e3300d04948409d8e25dbf7240d7893)

Game page with markdown description:

<img width="1342" alt="Game page with markdown description" src="https://user-images.githubusercontent.com/24768574/109476547-e7702180-7a2b-11eb-9c09-40e1965d3168.png">

Editing display for markdown:

<img width="990" alt="Editing page for markdown" src="https://user-images.githubusercontent.com/24768574/109476897-40d85080-7a2c-11eb-917a-8be628d60f10.png">

2021-03-01 09:22 UTC, alankbi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change description field to markdown](https://trello.com/c/f3Hnm6EC/264-change-description-field-to-markdown)

2021-03-02 06:04 UTC, zpChris requested changes
Requesting changes, as there is a slight issue (that we noticed on the call today) with the Markdown going past the bottom of the Game Page section. Additionally, we may want to move the placement of the "socket not connected error" - see the [screencast](https://www.loom.com/share/6c40bd28e3a44593925db1de490f9f32).

As for your note:
> It's very fancy and high-performing, though the tradeoff might be lower flexibility/reliance on a company product

I think that we definitely want to use an already-implemented Markdown editor in our app - there are lots of reliable sources out there, so we could switch it relatively easily if need-be, and I think the fanciness and high-performance is just a plus 😁

2021-03-02 07:43 UTC, alankbi commented on frontend/src/views/Game.tsx
> +              onChange={() => ''}
Without it I get a TypeScript "no overload matches this call" error, so I think it requires you to have something specified (unless there's a way around it if you know)

2021-03-02 07:45 UTC, alankbi commented on src/main/java/com/rocketden/main/model/problem/Problem.java
> +    @Column(columnDefinition = "TEXT")
The default I think is 255 characters (VARCHAR(255) or something like that). For reference, this is what ~230 characters look like: 

> Find the ASCII character that occurs most frequently in the string. If there is a tie, return the first character that appears in the string. Return an empty character if the string is empty. You can assume that the string is not null. 

Do you think any of our other string fields (for any database object) should be updated to be longer than 255?

2021-03-02 07:51 UTC, alankbi commented
Pushed a change that should fix the overflow error and also moved the error text to below the title/above the description - lmk your thoughts on that

2021-03-02 08:59 UTC, zpChris commented on src/main/java/com/rocketden/main/model/problem/Problem.java
> +    @Column(columnDefinition = "TEXT")
We may want to later, but I don't think there's any need to now - we can change it when necessary in another PR.

2021-03-02 09:20 UTC, zpChris approved these changes
LGTM! Thanks for making the overflow panel change, looks great 👍

2021-03-02 10:00 UTC, merged