Prevent switching room hosts to an inactive user
rocketden/main pull request #66
Opened 2020-10-19 19:39 UTC by alankbi

### List of Changes:

* Prevent hosts from selecting an inactive user to be host
* Refactor room host tests to include socket functionality
* Add `EqualsAndHashCode` to UserDto

### Notes:

* The reason it was necessary to refactor the room host tests is cause checking if a user is active/inactive depends on whether they're connected to the socket, which requires the same file setup as in `RoomSocketTests`

### Screencast and Images:

[New host change behavior demonstration](https://www.loom.com/share/1bae095cb2e44e9ca0a596c95fb8fb3c)

2020-10-20 02:13 UTC, zpChris requested changes
No large direct changes on this code, just one broad requested change: I think the "Make Host" button shouldn't be displayed on inactive users, and you could simply change the `HostActionCard.tsx` file and accept a parameter of whether the user is active or inactive. Let me know if this makes sense!

2020-10-20 17:01 UTC, alankbi commented on src/test/java/com/rocketden/main/service/RoomServiceTests.java
> +    private static final String SESSION_ID_2 = "session2";
Sounds good - I changed it to `abcdef` and `ghijkl` to indicate that and also avoid overlap with the `012345` room id just below

2020-10-20 17:16 UTC, alankbi commented
Updated to only show the make host button if the user is active - will note that the width of the action card is fixed so there's a lot of extra space around the kick button when this happens, but I figured we're going to redesign the action card eventually anyways so can deal with that later (or if you think we should do it now that's fine too, just leave a comment/request changes)

2020-10-20 18:20 UTC, zpChris commented on src/test/java/com/rocketden/main/service/RoomServiceTests.java
> +    private static final String SESSION_ID_2 = "session2";
Awesome, thanks!

2020-10-20 18:45 UTC, zpChris approved these changes
The changes look great! I think maintaining the current width, at least for now, is no problem at all. 👍

2020-10-21 04:09 UTC, helenli8181 approved these changes
Looks good! I also don't mind letting the action card stay as it is for now until we get to redesigning the pages. And since you got rid of the Make Host button for inactive users, theoretically the INACTIVE_USER error should never see daylight :)

2020-10-21 05:18 UTC, merged